-- ECOLI_DATA 테이블
-- ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE 존재
-- 대장균 개체의 ID(ID)와 자식의 수(CHILD_COUNT)를 출력하는 SQL 문을 작성
-- 자식이 없다면 자식의 수는 0으로 출력
-- 결과는 개체의 ID 에 대해 오름차순 정렬

SELECT P.ID, COUNT(C.PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA AS P
    LEFT JOIN ECOLI_DATA AS C
    ON P.ID = C.PARENT_ID
GROUP BY P.ID
ORDER BY P.ID;